# Generated by Django 5.2.8 on 2025-11-25 17:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Alimento',
                'verbose_name_plural': 'Categorias de Alimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('cliente', 'Cliente'), ('ong', 'ONG')], default='cliente', max_length=10, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('pct', 'Pacote')], default='kg', max_length=20, verbose_name='Unidade de Medida')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos', to='core.categoriaalimento', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da ONG')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('endereco_completo', models.TextField(verbose_name='Endereço Completo')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ongs/', verbose_name='Foto')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ong_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem do Doador')),
                ('data_doacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Doação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='core.alimento', verbose_name='Alimento')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_recebidas', to='core.ong', verbose_name='ONG Beneficiada')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_doacao'],
            },
        ),
        migrations.CreateModel(
            name='NecessidadeAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Necessária')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Recebida')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='core.alimento', verbose_name='Alimento')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='core.ong', verbose_name='ONG')),
            ],
            options={
                'verbose_name': 'Necessidade de Alimento',
                'verbose_name_plural': 'Necessidades de Alimentos',
                'ordering': ['-prioridade', 'alimento__nome'],
                'unique_together': {('ong', 'alimento')},
            },
        ),
    ]
